# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YFCommonTableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
pod 'SDWebImage'
pod 'Masonry','~> 1.0.2'

  # Pods for YFCommonTableView

end
